#!/usr/bin/env python3
"""
tools/train_mnist.py - train the MNIST classifier Ferrite's demo runs.

Trains a small MLP (784 -> 128 -> 10) in PyTorch, reports test accuracy, and
exports it to ONNX using only ops Ferrite's importer maps.

Why an explicit matmul instead of nn.Linear
-------------------------------------------
torch.nn.Linear exports as Gemm with transB=1, because PyTorch stores weights
as [out, in]. transB=1 is NOT an ONNX default, and Ferrite's importer warns
(correctly) that it cannot honour it. So the model holds its weights already
transposed as [in, out] and computes `x @ W + b`, which exports as MatMul +
Add -- both mapped, both exact. This mirrors tests/tiny_mlp.onnx.

Outputs
-------
  tests/mnist.onnx          the model the demo and the golden zoo load
  tools/mnist_samples.h     a handful of test digits embedded for the demo

Usage
-----
  pip install torch            # torchvision is NOT required
  python tools/train_mnist.py
  python tools/train_mnist.py --epochs 8 --seed 7
"""

import argparse
import gzip
import os
import struct
import sys
import urllib.request
from pathlib import Path

import numpy as np

try:
    import torch
    import torch.nn as nn
except ImportError:
    sys.exit("train_mnist.py needs PyTorch: pip install torch")

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "build" / "mnist-data"      # gitignored: /build/
ONNX_OUT = ROOT / "tests" / "mnist.onnx"
HEADER_OUT = ROOT / "tools" / "mnist_samples.h"

# yann.lecun.com rate-limits and often 404s now; this is the mirror torchvision
# itself falls back to.
MIRROR = "https://ossci-datasets.s3.amazonaws.com/mnist/"
FILES = {
    "train_x": "train-images-idx3-ubyte.gz",
    "train_y": "train-labels-idx1-ubyte.gz",
    "test_x": "t10k-images-idx3-ubyte.gz",
    "test_y": "t10k-labels-idx1-ubyte.gz",
}


def fetch(name):
    CACHE.mkdir(parents=True, exist_ok=True)
    dest = CACHE / name
    if dest.exists() and dest.stat().st_size > 0:
        return dest
    url = MIRROR + name
    print(f"  downloading {name} ...", flush=True)
    urllib.request.urlretrieve(url, dest)
    return dest


def read_idx(path):
    """Parse an IDX file (the MNIST container format)."""
    with gzip.open(path, "rb") as f:
        magic, = struct.unpack(">I", f.read(4))
        ndim = magic & 0xFF
        dims = struct.unpack(">" + "I" * ndim, f.read(4 * ndim))
        buf = f.read()
    return np.frombuffer(buf, dtype=np.uint8).reshape(dims)


def load_mnist():
    print("MNIST data:")
    xs = {k: read_idx(fetch(v)) for k, v in FILES.items()}
    train_x = xs["train_x"].astype(np.float32).reshape(-1, 784) / 255.0
    test_x = xs["test_x"].astype(np.float32).reshape(-1, 784) / 255.0
    return train_x, xs["train_y"].astype(np.int64), test_x, xs["test_y"].astype(np.int64)


class MLP(nn.Module):
    """784 -> 128 -> 10 with weights stored [in, out] so export is MatMul+Add."""

    def __init__(self, hidden=128):
        super().__init__()
        # Kaiming-ish init, matched to the [in, out] layout.
        self.w1 = nn.Parameter(torch.randn(784, hidden) * (2.0 / 784) ** 0.5)
        self.b1 = nn.Parameter(torch.zeros(hidden))
        self.w2 = nn.Parameter(torch.randn(hidden, 10) * (2.0 / hidden) ** 0.5)
        self.b2 = nn.Parameter(torch.zeros(10))

    def forward(self, x):
        x = torch.relu(torch.matmul(x, self.w1) + self.b1)
        return torch.matmul(x, self.w2) + self.b2      # logits


def accuracy(model, x, y, batch=1000):
    model.eval()
    correct = 0
    with torch.no_grad():
        for i in range(0, len(x), batch):
            logits = model(torch.from_numpy(x[i:i + batch]))
            correct += (logits.argmax(1).numpy() == y[i:i + batch]).sum()
    return correct / len(x)


def write_samples_header(test_x, test_y, model, n=10):
    """Embed one correctly-classified example of each digit for the C demo."""
    model.eval()
    with torch.no_grad():
        preds = model(torch.from_numpy(test_x)).argmax(1).numpy()

    chosen = []
    for digit in range(n):
        hits = np.where((test_y == digit) & (preds == digit))[0]
        if len(hits) == 0:                      # fall back to any example
            hits = np.where(test_y == digit)[0]
        chosen.append(int(hits[0]))

    lines = [
        "/* tools/mnist_samples.h - GENERATED by tools/train_mnist.py.",
        " *",
        " * One correctly-classified MNIST test digit per class, embedded so the",
        " * demo needs no data files. Pixels are row-major 28x28, already scaled",
        " * to [0,1] exactly as training did (raw byte / 255).",
        " */",
        "#ifndef FERRITE_MNIST_SAMPLES_H",
        "#define FERRITE_MNIST_SAMPLES_H",
        "",
        f"#define MNIST_N_SAMPLES {len(chosen)}",
        "#define MNIST_PIXELS    784",
        "",
        f"static const int mnist_labels[{len(chosen)}] = {{",
        "    " + ", ".join(str(int(test_y[i])) for i in chosen),
        "};",
        "",
        f"static const float mnist_images[{len(chosen)}][784] = {{",
    ]
    for idx in chosen:
        img = test_x[idx]
        lines.append(f"    {{ /* label {int(test_y[idx])} */")
        for r in range(28):
            row = img[r * 28:(r + 1) * 28]
            lines.append("        " + ", ".join(f"{v:.6f}f" for v in row) + ",")
        lines.append("    },")
    lines += ["};", "", "#endif /* FERRITE_MNIST_SAMPLES_H */", ""]

    HEADER_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {HEADER_OUT.relative_to(ROOT)} ({len(chosen)} digits)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--epochs", type=int, default=6)
    ap.add_argument("--hidden", type=int, default=128)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--batch", type=int, default=128)
    ap.add_argument("--seed", type=int, default=20260922)
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)

    train_x, train_y, test_x, test_y = load_mnist()
    print(f"  train {train_x.shape}, test {test_x.shape}")

    model = MLP(args.hidden)
    opt = torch.optim.Adam(model.parameters(), lr=args.lr)
    loss_fn = nn.CrossEntropyLoss()

    tx = torch.from_numpy(train_x)
    ty = torch.from_numpy(train_y)

    print(f"\nTraining {args.epochs} epochs (784 -> {args.hidden} -> 10):")
    for epoch in range(args.epochs):
        model.train()
        perm = torch.randperm(len(tx))
        total = 0.0
        for i in range(0, len(tx), args.batch):
            idx = perm[i:i + args.batch]
            opt.zero_grad()
            loss = loss_fn(model(tx[idx]), ty[idx])
            loss.backward()
            opt.step()
            total += loss.item() * len(idx)
        acc = accuracy(model, test_x, test_y)
        print(f"  epoch {epoch + 1}/{args.epochs}  "
              f"loss {total / len(tx):.4f}  test acc {acc * 100:.2f}%")

    final = accuracy(model, test_x, test_y)
    print(f"\nPyTorch test accuracy: {final * 100:.2f}% "
          f"({int(round(final * len(test_x)))}/{len(test_x)})")

    # Export. opset 13, batch dim fixed at 1 -- Ferrite infers the rest.
    ONNX_OUT.parent.mkdir(parents=True, exist_ok=True)
    model.eval()
    torch.onnx.export(
        model,
        torch.zeros(1, 784),
        str(ONNX_OUT),
        input_names=["input"],
        output_names=["logits"],
        opset_version=13,
        dynamo=False,
    )
    print(f"  wrote {ONNX_OUT.relative_to(ROOT)} "
          f"({ONNX_OUT.stat().st_size / 1024:.0f} KB fp32)")

    write_samples_header(test_x, test_y, model)

    # Raw dumps so tools/mnist_eval can measure Ferrite's own accuracy
    # over the full test set. They live under build/ (gitignored).
    (CACHE / 'test_images.bin').write_bytes(test_x.astype('<f4').tobytes())
    (CACHE / 'test_labels.bin').write_bytes(test_y.astype('uint8').tobytes())
    print(f'  wrote {CACHE.relative_to(ROOT)}/test_images.bin + test_labels.bin')

    print("\nNext:")
    print("  cmake --build build --target demo_mnist && ./build/demo_mnist")
    print("  python tools/mnist_accuracy.py --run-model build/run_model")


if __name__ == "__main__":
    main()
